---
# defaults file for megasync
mega_gpg_key_url: https://mega.nz/linux/repo/xUbuntu_{{ ansible_distribution_version }}/Release.key
mega_gpg_keyring_path: /usr/share/keyrings/megasync-archive-keyring.gpg
mega_repo_url: https://mega.nz/linux/repo/xUbuntu_{{ ansible_distribution_version }}
mega_package_state: present
mega_install_megacmd: true
